import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/componets/Navbar";
import Footer from "@/componets/Footer";
import SessionWrapper from "@/componets/SessionWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Fund Collector - HELP THE NEEDY",
  description: "Generated by Manvar",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="min-h-screen flex flex-col [background:radial-gradient(125%_125%_at_50%_10%,#000_40%,#63e_100%)] text-white"
      >
        <SessionWrapper>
          <Navbar />
          
          {/* Main content grows to fill remaining space */}
          <main className="flex-grow">
            {children}
          </main>
          
          <Footer />
        </SessionWrapper>
      </body>
    </html>
  );
}

