import React from 'react'

const page = () => {
  return (
    <div>
      I am about page
    </div>
  )
}

export default page
export const metadata = {
    title: "About US",
    description: "Generated by create next app",
  };