import React from 'react'
import Script from 'next/script'

const page = () => {
  return (
    <div>
        <Script>
            {`alert("Welcome to Contact Page")`}
        </Script>
      I am Contact Page
    </div>
  )
}

export default page
export const metadata = {
    title: "Contact MyApp",
    description: "Generated by create next app",
  };